# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Write Secret Key Ring File
        uses: joutvhu/write-file@v1
        with:
          path: secrets/secret-key.gpg
          contents: ${{ secrets.GPG_SECRET_KEY_BASE64 }}
          write_mode: overwrite
          encoding: base64

      - name: Write Gradle Properties File
        uses: joutvhu/write-file@v1
        with:
          path: gradle.properties
          contents: ${{ secrets.GRADLE_SECRET_PROPERTIES }}
          write_mode: overwrite

      - name: Build with Gradle
        run: gradle clean build

      - name: Publish to Sonatype Packages
        run: gradle publishMavenPublicationToSonatypeRepository

#      - name: Publish to GitHub Packages
#        run: gradle publishMavenPublicationToGithubRepository
