package com.joutvhu.fixedwidth.parser.processor.generator;

import com.joutvhu.fixedwidth.parser.processor.model.ModelClass;
import com.joutvhu.fixedwidth.parser.processor.model.ModelField;

import javax.annotation.processing.Filer;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

/**
 * Generates {@code <ClassName>$FixedAccessor} source files that implement
 * {@link com.joutvhu.fixedwidth.parser.codegen.FixedFieldAccessor}.
 *
 * <p>The generated class uses a {@code switch} on the field name and calls
 * the model's getter/setter methods directly — zero Reflection at runtime.
 *
 * @author Giao Ho
 * @since 2.0.0
 */
public final class AccessorGenerator {

    private final ProcessingEnvironment processingEnv;

    public AccessorGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    /**
     * Generates the {@code $FixedAccessor} class for the given model.
     * Fields that lack a public getter or setter are skipped (the runtime
     * will fall back to Reflection for those fields).
     */
    public void generate(ModelClass model) {
        List<ModelField> fields = model.getAccessibleFields();
        if (fields.isEmpty()) {
            // No accessible fields — nothing to generate.
            // The runtime Reflection fallback will handle everything.
            return;
        }

        String accessorQualifiedName = model.getQualifiedClassName() + "$FixedAccessor";
        String accessorSimpleName = model.getAccessorSimpleName();

        Filer filer = processingEnv.getFiler();
        try {
            Element[] originatingElements = {model.getTypeElement()};
            JavaFileObject sourceFile = filer.createSourceFile(
                accessorQualifiedName, originatingElements);

            try (PrintWriter w = new PrintWriter(sourceFile.openWriter())) {
                // Package declaration
                if (!model.getPackageName().isEmpty()) {
                    w.println("package " + model.getPackageName() + ";");
                    w.println();
                }

                // Import
                w.println("import com.joutvhu.fixedwidth.parser.codegen.FixedFieldAccessor;");
                w.println("import com.joutvhu.fixedwidth.parser.codegen.FixedMetaProvider;");
                w.println("import com.joutvhu.fixedwidth.parser.codegen.FieldMetadata;");
                w.println("import com.joutvhu.fixedwidth.parser.domain.Alignment;");
                w.println("import com.joutvhu.fixedwidth.parser.domain.KeepPadding;");
                w.println("import java.util.HashMap;");
                w.println("import java.util.Map;");
                w.println("import java.util.Collections;");
                w.println();

                // Class declaration
                w.println("/**");
                w.println(" * Generated accessor and meta provider for {@link " + model.getQualifiedClassName() + "}.");
                w.println(" * Eliminates Reflection-based field access and metadata extraction on the hot path.");
                w.println(" *");
                w.println(" * <p>This class is generated by the fixed-width-parser annotation processor.");
                w.println(" * Do not edit manually.");
                w.println(" */");
                w.println("public final class " + accessorSimpleName
                    + " implements FixedFieldAccessor<" + model.getSimpleClassName() + ">, "
                    + "FixedMetaProvider<" + model.getSimpleClassName() + "> {");
                w.println();
                
                // Static metadata cache
                w.println("    private static final Map<String, FieldMetadata> META;");
                w.println("    static {");
                w.println("        Map<String, FieldMetadata> map = new HashMap<>();");
                for (ModelField field : model.getFields()) {
                    w.print("        map.put(\"" + field.getFieldName() + "\", new FieldMetadata(");
                    w.print("\"" + field.getFieldName() + "\", ");
                    
                    // Note: label extraction requires @FixedField.label(), we didn't extract it, 
                    // so we pass null and let TypeInfoSetter build it dynamically if needed.
                    w.print("null, ");
                    
                    w.print(field.getStart() + ", ");
                    w.print(field.getLength() + ", ");
                    w.print(field.isRequire() + ", ");
                    
                    // Characters need to be formatted correctly.
                    w.print(formatChar(field.getPadding()) + ", ");
                    w.print(formatChar(field.getNullPadding()) + ", ");
                    
                    w.print(field.getKeepPadding() == null ? "null" : "KeepPadding." + field.getKeepPadding());
                    w.print(", ");
                    
                    w.print(field.getAlignment() == null ? "null" : "Alignment." + field.getAlignment());
                    w.println("));");
                }
                w.println("        META = Collections.unmodifiableMap(map);");
                w.println("    }");
                w.println();

                // targetClass()
                w.println("    @Override");
                w.println("    public Class<" + model.getSimpleClassName() + "> targetClass() {");
                w.println("        return " + model.getSimpleClassName() + ".class;");
                w.println("    }");
                w.println();
                
                // getFieldMetadata()
                w.println("    @Override");
                w.println("    public Map<String, FieldMetadata> getFieldMetadata() {");
                w.println("        return META;");
                w.println("    }");
                w.println();

                // set()
                w.println("    @Override");
                w.println("    public void set(" + model.getSimpleClassName()
                    + " target, String fieldName, Object value) {");
                w.println("        switch (fieldName) {");
                for (ModelField field : fields) {
                    w.println("            case \"" + field.getFieldName() + "\":");
                    String cast = getCastExpression(field);
                    w.println("                target." + field.getSetterName()
                        + "(" + cast + ");");
                    w.println("                break;");
                }
                w.println("            default:");
                w.println("                break;");
                w.println("        }");
                w.println("    }");
                w.println();

                // get()
                w.println("    @Override");
                w.println("    public Object get(" + model.getSimpleClassName()
                    + " target, String fieldName) {");
                w.println("        switch (fieldName) {");
                for (ModelField field : fields) {
                    w.println("            case \"" + field.getFieldName() + "\":");
                    w.println("                return target." + field.getGetterName() + "();");
                }
                w.println("            default:");
                w.println("                return null;");
                w.println("        }");
                w.println("    }");

                w.println("}");
            }
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(
                javax.tools.Diagnostic.Kind.ERROR,
                "Failed to generate accessor for " + model.getQualifiedClassName()
                    + ": " + e.getMessage(),
                model.getTypeElement());
        }
    }

    /**
     * Returns a cast expression for the setter parameter.
     * Primitive types need unboxing casts; reference types use a simple cast.
     */
    private String getCastExpression(ModelField field) {
        // Simple heuristic for casting when reading from Object
        String typeName = field.getFieldType().toString();
        
        // If it's a primitive, use the wrapper class for casting and let auto-unboxing handle it
        if (typeName.equals("int")) return "(java.lang.Integer) value";
        if (typeName.equals("long")) return "(java.lang.Long) value";
        if (typeName.equals("double")) return "(java.lang.Double) value";
        if (typeName.equals("float")) return "(java.lang.Float) value";
        if (typeName.equals("boolean")) return "(java.lang.Boolean) value";
        if (typeName.equals("char")) return "(java.lang.Character) value";
        if (typeName.equals("short")) return "(java.lang.Short) value";
        if (typeName.equals("byte")) return "(java.lang.Byte) value";
        
        return "(" + typeName + ") value";
    }

    private String formatChar(Character c) {
        if (c == null) return "null";
        switch (c) {
            case '\'': return "'\\''";
            case '\\': return "'\\\\'";
            case '\t': return "'\\t'";
            case '\n': return "'\\n'";
            case '\r': return "'\\r'";
            case '\b': return "'\\b'";
            case '\f': return "'\\f'";
            default:
                // Handle non-printable ascii just in case
                if (c < 32 || c > 126) {
                    return String.format("'\\u%04x'", (int) c);
                }
                return "'" + c + "'";
        }
    }
}
