package com.joutvhu.fixedwidth.parser.processor.generator;

import com.joutvhu.fixedwidth.parser.processor.model.ModelClass;
import com.joutvhu.fixedwidth.parser.processor.model.ModelField;

import javax.annotation.processing.Filer;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

/**
 * Generates a single {@code <ClassName>$FixedWidth} companion class per model that
 * implements both {@link com.joutvhu.fixedwidth.parser.codegen.FixedFieldAccessor}
 * and {@link com.joutvhu.fixedwidth.parser.codegen.FixedMetaProvider}.
 *
 * <p>Combining both roles in one class means:
 * <ul>
 *   <li>One generated file per model instead of two</li>
 *   <li>One ServiceLoader entry per model (registered under
 *       {@code FixedFieldAccessor} — the runtime looks up both interfaces
 *       through {@link com.joutvhu.fixedwidth.parser.codegen.FixedCompanionRegistry})</li>
 *   <li>Slightly smaller class-loading overhead at startup</li>
 * </ul>
 *
 * <p>Fields without public getter/setter are excluded from the accessor
 * {@code get}/{@code set} switch but are still included in the metadata map.
 *
 * @author Giao Ho
 * @since 2.0.0
 */
public final class FixedCompanionGenerator {

    private final ProcessingEnvironment processingEnv;

    public FixedCompanionGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    /**
     * Generates the {@code $FixedWidth} companion class for the given model.
     * Skipped entirely when the model has no {@code @FixedField}-annotated fields.
     */
    public void generate(ModelClass model) {
        List<ModelField> allFields        = model.getFields();
        List<ModelField> accessibleFields = model.getAccessibleFields();

        if (allFields.isEmpty()) {
            return;
        }

        String companionQualifiedName = model.getQualifiedClassName() + "$FixedWidth";
        String companionSimpleName    = model.getSimpleClassName()    + "$FixedWidth";

        Filer filer = processingEnv.getFiler();
        try {
            Element[] originatingElements = {model.getTypeElement()};
            JavaFileObject sourceFile = filer.createSourceFile(
                companionQualifiedName, originatingElements);

            try (PrintWriter w = new PrintWriter(sourceFile.openWriter())) {
                writePackage(w, model);
                writeImports(w);
                writeClassJavadoc(w, model);
                writeClassDeclaration(w, model, companionSimpleName);
                writeMetaStaticBlock(w, allFields);
                writeTargetClass(w, model);
                writeGetFieldMetadata(w);
                if (!accessibleFields.isEmpty()) {
                    writeSet(w, model, accessibleFields);
                    writeGet(w, model, accessibleFields);
                } else {
                    writeSetNoOp(w, model);
                    writeGetNoOp(w, model);
                }
                w.println("}");
            }
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(
                javax.tools.Diagnostic.Kind.ERROR,
                "Failed to generate companion for " + model.getQualifiedClassName()
                    + ": " + e.getMessage(),
                model.getTypeElement());
        }
    }

    // ── Section writers ───────────────────────────────────────────────────────

    private void writePackage(PrintWriter w, ModelClass model) {
        if (!model.getPackageName().isEmpty()) {
            w.println("package " + model.getPackageName() + ";");
            w.println();
        }
    }

    private void writeImports(PrintWriter w) {
        w.println("import com.joutvhu.fixedwidth.parser.codegen.FieldMetadata;");
        w.println("import com.joutvhu.fixedwidth.parser.codegen.FixedFieldAccessor;");
        w.println("import com.joutvhu.fixedwidth.parser.codegen.FixedMetaProvider;");
        w.println("import com.joutvhu.fixedwidth.parser.domain.Alignment;");
        w.println("import com.joutvhu.fixedwidth.parser.domain.KeepPadding;");
        w.println("import java.util.Collections;");
        w.println("import java.util.HashMap;");
        w.println("import java.util.Map;");
        w.println();
    }

    private void writeClassJavadoc(PrintWriter w, ModelClass model) {
        w.println("/**");
        w.println(" * Generated companion for {@link " + model.getQualifiedClassName() + "}.");
        w.println(" * Implements both field accessor (zero Reflection get/set) and");
        w.println(" * metadata provider (pre-computed start/length/padding/alignment).");
        w.println(" *");
        w.println(" * <p>This class is generated by the fixed-width-parser annotation processor.");
        w.println(" * Do not edit manually.");
        w.println(" */");
    }

    private void writeClassDeclaration(PrintWriter w, ModelClass model, String simpleName) {
        w.println("public final class " + simpleName
            + " implements FixedFieldAccessor<" + model.getSimpleClassName() + ">,"
            + " FixedMetaProvider<" + model.getSimpleClassName() + "> {");
        w.println();
    }

    private void writeMetaStaticBlock(PrintWriter w, List<ModelField> fields) {
        w.println("    private static final Map<String, FieldMetadata> META;");
        w.println("    static {");
        w.println("        Map<String, FieldMetadata> map = new HashMap<>();");
        for (ModelField field : fields) {
            w.print("        map.put(\"" + field.getFieldName() + "\", new FieldMetadata(");
            w.print("\"" + field.getFieldName() + "\", ");
            w.print("null, ");   // label — filled by runtime if needed
            w.print(field.getStart() + ", ");
            w.print(field.getLength() + ", ");
            w.print(field.isRequire() + ", ");
            w.print(formatChar(field.getPadding()) + ", ");
            w.print(formatChar(field.getNullPadding()) + ", ");
            w.print(field.getKeepPadding() == null ? "null" : "KeepPadding." + field.getKeepPadding());
            w.print(", ");
            w.print(field.getAlignment() == null ? "null" : "Alignment." + field.getAlignment());
            w.println("));");
        }
        w.println("        META = Collections.unmodifiableMap(map);");
        w.println("    }");
        w.println();
    }

    private void writeTargetClass(PrintWriter w, ModelClass model) {
        w.println("    @Override");
        w.println("    public Class<" + model.getSimpleClassName() + "> targetClass() {");
        w.println("        return " + model.getSimpleClassName() + ".class;");
        w.println("    }");
        w.println();
    }

    private void writeGetFieldMetadata(PrintWriter w) {
        w.println("    @Override");
        w.println("    public Map<String, FieldMetadata> getFieldMetadata() {");
        w.println("        return META;");
        w.println("    }");
        w.println();
    }

    private void writeSet(PrintWriter w, ModelClass model, List<ModelField> fields) {
        w.println("    @Override");
        w.println("    public void set(" + model.getSimpleClassName()
            + " target, String fieldName, Object value) {");
        w.println("        switch (fieldName) {");
        for (ModelField field : fields) {
            w.println("            case \"" + field.getFieldName() + "\":");
            w.println("                target." + field.getSetterName()
                + "(" + getCastExpression(field) + ");");
            w.println("                break;");
        }
        w.println("            default:");
        w.println("                break;");
        w.println("        }");
        w.println("    }");
        w.println();
    }

    private void writeSetNoOp(PrintWriter w, ModelClass model) {
        w.println("    @Override");
        w.println("    public void set(" + model.getSimpleClassName()
            + " target, String fieldName, Object value) {");
        w.println("        // No accessible fields — Reflection fallback handles set");
        w.println("    }");
        w.println();
    }

    private void writeGet(PrintWriter w, ModelClass model, List<ModelField> fields) {
        w.println("    @Override");
        w.println("    public Object get(" + model.getSimpleClassName()
            + " target, String fieldName) {");
        w.println("        switch (fieldName) {");
        for (ModelField field : fields) {
            w.println("            case \"" + field.getFieldName() + "\":");
            w.println("                return target." + field.getGetterName() + "();");
        }
        w.println("            default:");
        w.println("                return null;");
        w.println("        }");
        w.println("    }");
        w.println();
    }

    private void writeGetNoOp(PrintWriter w, ModelClass model) {
        w.println("    @Override");
        w.println("    public Object get(" + model.getSimpleClassName()
            + " target, String fieldName) {");
        w.println("        // No accessible fields — Reflection fallback handles get");
        w.println("        return null;");
        w.println("    }");
        w.println();
    }

    // ── Type helpers ──────────────────────────────────────────────────────────

    /**
     * Returns a cast expression for the setter parameter using the erased type
     * name (strips type-use annotations that javac injects into
     * {@link javax.lang.model.type.TypeMirror#toString()}).
     */
    private String getCastExpression(ModelField field) {
        String typeName = processingEnv.getTypeUtils()
            .erasure(field.getFieldType()).toString();

        if (typeName.equals("int"))     return "(java.lang.Integer) value";
        if (typeName.equals("long"))    return "(java.lang.Long) value";
        if (typeName.equals("double"))  return "(java.lang.Double) value";
        if (typeName.equals("float"))   return "(java.lang.Float) value";
        if (typeName.equals("boolean")) return "(java.lang.Boolean) value";
        if (typeName.equals("char"))    return "(java.lang.Character) value";
        if (typeName.equals("short"))   return "(java.lang.Short) value";
        if (typeName.equals("byte"))    return "(java.lang.Byte) value";

        return "(" + typeName + ") value";
    }

    private String formatChar(Character c) {
        if (c == null) return "null";
        switch (c) {
            case '\'': return "'\\''";
            case '\\': return "'\\\\'";
            case '\t': return "'\\t'";
            case '\n': return "'\\n'";
            case '\r': return "'\\r'";
            case '\b': return "'\\b'";
            case '\f': return "'\\f'";
            default:
                if (c < 32 || c > 126) {
                    return String.format("'\\u%04x'", (int) c);
                }
                return "'" + c + "'";
        }
    }
}
