package com.joutvhu.fixedwidth.parser.processor.generator;

import com.joutvhu.fixedwidth.parser.processor.model.ModelClass;
import com.joutvhu.fixedwidth.parser.processor.model.ModelField;

import javax.annotation.processing.Filer;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

/**
 * Generates {@code <ClassName>$FixedMeta} source files that implement
 * {@link com.joutvhu.fixedwidth.parser.codegen.FixedMetaProvider}.
 *
 * <p>The generated class pre-computes {@code start}, {@code length}, padding,
 * and alignment for every {@code @FixedField} at compile time, eliminating
 * annotation scanning on the cold-start path.
 *
 * <p>The generated class is separate from {@code $FixedAccessor} so that
 * users who only want metadata pre-computation (e.g. for GraalVM) can use it
 * independently of the accessor.
 *
 * @author Giao Ho
 * @since 2.0.0
 */
public final class MetaGenerator {

    private final ProcessingEnvironment processingEnv;

    public MetaGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    /**
     * Generates the {@code $FixedMeta} class for the given model.
     * All {@code @FixedField}-annotated fields are included, regardless of
     * whether they have public getters/setters.
     */
    public void generate(ModelClass model) {
        List<ModelField> fields = model.getFields();
        if (fields.isEmpty()) {
            return;
        }

        String metaQualifiedName = model.getQualifiedClassName() + "$FixedMeta";
        String metaSimpleName = model.getSimpleClassName() + "$FixedMeta";

        Filer filer = processingEnv.getFiler();
        try {
            Element[] originatingElements = {model.getTypeElement()};
            JavaFileObject sourceFile = filer.createSourceFile(
                metaQualifiedName, originatingElements);

            try (PrintWriter w = new PrintWriter(sourceFile.openWriter())) {
                // Package declaration
                if (!model.getPackageName().isEmpty()) {
                    w.println("package " + model.getPackageName() + ";");
                    w.println();
                }

                // Imports
                w.println("import com.joutvhu.fixedwidth.parser.codegen.FieldMetadata;");
                w.println("import com.joutvhu.fixedwidth.parser.codegen.FixedMetaProvider;");
                w.println("import com.joutvhu.fixedwidth.parser.domain.Alignment;");
                w.println("import com.joutvhu.fixedwidth.parser.domain.KeepPadding;");
                w.println("import java.util.Collections;");
                w.println("import java.util.HashMap;");
                w.println("import java.util.Map;");
                w.println();

                // Class declaration
                w.println("/**");
                w.println(" * Generated metadata provider for {@link " + model.getQualifiedClassName() + "}.");
                w.println(" * Pre-computes start/length/padding/alignment for every @FixedField at compile time.");
                w.println(" *");
                w.println(" * <p>This class is generated by the fixed-width-parser annotation processor.");
                w.println(" * Do not edit manually.");
                w.println(" */");
                w.println("public final class " + metaSimpleName
                    + " implements FixedMetaProvider<" + model.getSimpleClassName() + "> {");
                w.println();

                // Static metadata map — built once at class-init time
                w.println("    private static final Map<String, FieldMetadata> META;");
                w.println("    static {");
                w.println("        Map<String, FieldMetadata> map = new HashMap<>();");
                for (ModelField field : fields) {
                    w.print("        map.put(\"" + field.getFieldName() + "\", new FieldMetadata(");
                    w.print("\"" + field.getFieldName() + "\", ");
                    w.print("null, ");  // label — not extracted at compile time; runtime fills it
                    w.print(field.getStart() + ", ");
                    w.print(field.getLength() + ", ");
                    w.print(field.isRequire() + ", ");
                    w.print(formatChar(field.getPadding()) + ", ");
                    w.print(formatChar(field.getNullPadding()) + ", ");
                    w.print(field.getKeepPadding() == null ? "null" : "KeepPadding." + field.getKeepPadding());
                    w.print(", ");
                    w.print(field.getAlignment() == null ? "null" : "Alignment." + field.getAlignment());
                    w.println("));");
                }
                w.println("        META = Collections.unmodifiableMap(map);");
                w.println("    }");
                w.println();

                // targetClass()
                w.println("    @Override");
                w.println("    public Class<" + model.getSimpleClassName() + "> targetClass() {");
                w.println("        return " + model.getSimpleClassName() + ".class;");
                w.println("    }");
                w.println();

                // getFieldMetadata()
                w.println("    @Override");
                w.println("    public Map<String, FieldMetadata> getFieldMetadata() {");
                w.println("        return META;");
                w.println("    }");
                w.println("}");
            }
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(
                javax.tools.Diagnostic.Kind.ERROR,
                "Failed to generate meta provider for " + model.getQualifiedClassName()
                    + ": " + e.getMessage(),
                model.getTypeElement());
        }
    }

    private String formatChar(Character c) {
        if (c == null) return "null";
        switch (c) {
            case '\'': return "'\\''";
            case '\\': return "'\\\\'";
            case '\t': return "'\\t'";
            case '\n': return "'\\n'";
            case '\r': return "'\\r'";
            case '\b': return "'\\b'";
            case '\f': return "'\\f'";
            default:
                if (c < 32 || c > 126) {
                    return String.format("'\\u%04x'", (int) c);
                }
                return "'" + c + "'";
        }
    }
}
