package com.joutvhu.fixedwidth.parser.codegen;

/**
 * Compile-time-generated accessor for a single {@code @FixedObject} class.
 * Implementations are generated by the APT processor and eliminate
 * {@link java.lang.reflect.Field#get}/{@link java.lang.reflect.Field#set}
 * calls on the parse/export hot path.
 *
 * @param <T> the {@code @FixedObject} class
 * @author Giao Ho
 * @since 2.0.0
 */
public interface FixedFieldAccessor<T> {

    /**
     * The model class this accessor targets.
     */
    Class<T> targetClass();

    /**
     * Set the named field on {@code target} to {@code value}.
     *
     * @param target    the model instance
     * @param fieldName the field name as declared in the model
     * @param value     the value to set (may be {@code null})
     */
    void set(T target, String fieldName, Object value);

    /**
     * Get the named field value from {@code target}.
     *
     * @param target    the model instance
     * @param fieldName the field name as declared in the model
     * @return the field value, or {@code null} if the field is unknown
     */
    Object get(T target, String fieldName);
}
